title: My First Github Pages Site
author: nibudd
email: nibudd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description of my site. It uses great adjectives
  and has laudable diction.

# social links
twitter_username: nibudd
github_username:  nibudd

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
